# Jekyll configuration

title: catfish
name: catfish
description: Shon?

# Url is currently only used only for the RSS feed in feed.xml
url: http://minnowo.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Minno
copyright: 2023

social:
  rss: feed.xml

show_footer: false

collections:
  links:
    output: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: minno
comments: false

permalink: /:year/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  # syntax_highlighter: rouge


exclude: ['README.md', 'LICENSE']
