# Jekyll configuration

title: catfish
name: catfish
description: Shon?

permalink: /:year/:title/

# Url is currently only used only for the RSS feed in feed.xml
# Don't have it end in a /
url: https://minnowo.github.io
source_code: https://github.com/minnowo/minnowo.github.io

# For a project page here should be a project name. 
# Otherwise (for user's/organization's page leave it empty)
baseurl: ''

  
# Footer stuff
footer:
  visible: true
    
  show_source_code: true
  show_rss_url: true
  show_license_url: false
  show_appleworm: true

collections:
  posts:
    output: true
  links:
    output: true

markdown: kramdown

kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  # syntax_highlighter: rouge
