site_name: OwO
site_description: ""
site_url: ''
repo_url: https://github.com/Minnowo/minnowo.github.io
repo_name: Minnowo/minnowo.github.io
use_directory_urls: false

plugins: []

nav:
  - index.md
  - Games:
    - games.md
  - Software:
    - software-myself.md
    - software-download.md
    - software-gediting.md
    - software-extensions.md
    - software-video.md
    - software-audio.md
    - software-other.md
  - Websites:
    - website-filehosting.md
    - website-ipcheck.md
    - website-piracy.md
    - website-other.md


theme:
  name: material
  palette:
    # - media: "(prefers-color-scheme: light)" 
    #   scheme: default
    #   primary: blue grey
    #   accent: blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/logo-white.svg
  favicon: assets/logo-white.svg
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - content.tabs.link
    - navigation.top
    - search.suggest
    - content.code.annotate
    #- navigation.indexes
  icon:
    repo: fontawesome/brands/github